#!/bin/bash

echo "🎯 AUTO CLICK TOOL - APK BUILD HƯỚNG DẪN"
echo "======================================"
echo ""
echo "📋 Để có APK ngay trong 5 phút:"
echo ""
echo "1️⃣ TẠO GITHUB REPOSITORY:"
echo "   - Vào https://github.com/new"
echo "   - Tên repo: auto-click-tool"
echo "   - Public repository"
echo "   - Không tick 'Add a README file'"
echo ""
echo "2️⃣ UPLOAD CODE:"
echo "   git remote add origin https://github.com/[USERNAME]/auto-click-tool.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "3️⃣ TỰ ĐỘNG BUILD APK:"
echo "   - GitHub Actions sẽ tự động chạy"
echo "   - Chờ 3-5 phút để build hoàn thành"
echo "   - APK sẽ sẵn sàng tải về"
echo ""
echo "4️⃣ TẢI APK:"
echo "   - Vào tab 'Actions' trong repository"
echo "   - Chọn build có dấu ✅ (xanh)"
echo "   - Download 'auto-click-tool-debug'"
echo "   - Giải nén và cài APK"
echo ""
echo "🚀 HOẶC TẠO RELEASE:"
echo "   - Vào tab 'Actions'"
echo "   - Chọn 'Release APK'"
echo "   - Click 'Run workflow'"
echo "   - Nhập version (vd: v1.0.0)"
echo "   - APK sẽ có trong Releases"
echo ""
echo "📱 APK SẴN SÀNG SỬ DỤNG!"
echo "========================="
echo "✅ Tự động click chính xác"
echo "✅ Overlay điều khiển"  
echo "✅ Quản lý nhiều điểm click"
echo "✅ Giao diện hiện đại"
echo "✅ Android 7.0+"
echo ""
echo "💡 Lưu ý: Nhớ cấp quyền Accessibility và Overlay sau khi cài!"
