#!/bin/bash

# Script tự động setup GitHub repository và build APK

echo "🚀 Auto Click Tool - Setup & Build Script"
echo "========================================"

# Kiểm tra git đã init chưa
if [ ! -d ".git" ]; then
    echo "📁 Initializing git repository..."
    git init
    git add .
    git commit -m "Initial commit: Auto Click Tool Android app"
fi

# Tạo .gitignore cho Android
cat > .gitignore << EOF
# Built application files
*.apk
*.aar
*.ap_
*.aab

# Files for the ART/Dalvik VM
*.dex

# Java class files
*.class

# Generated files
bin/
gen/
out/
release/

# Gradle files
.gradle/
build/

# Local configuration file (sdk path, etc)
local.properties

# Proguard folder generated by Eclipse
proguard/

# Log Files
*.log

# Android Studio Navigation editor temp files
.navigation/

# Android Studio captures folder
captures/

# IntelliJ
*.iml
.idea/workspace.xml
.idea/tasks.xml
.idea/gradle.xml
.idea/assetWizard.xml
.idea/dictionaries
.idea/libraries
.idea/jarRepositories.xml
.idea/caches
.idea/modules.xml
.idea/.name
.idea/compiler.xml
.idea/copyright/profiles_settings.xml
.idea/encodings.xml
.idea/misc.xml
.idea/navEditor.xml
.idea/scopes/scope_settings.xml
.idea/vcs.xml
.idea/jsLibraryMappings.xml
.idea/datasources.xml
.idea/dataSources.ids
.idea/sqlDataSources.xml
.idea/dynamic.xml
.idea/uiDesigner.xml

# OS-specific files
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
ehthumbs.db
Thumbs.db

# External native build folder generated in Android Studio 2.2 and later
.externalNativeBuild
.cxx/

# Google Services (e.g. APIs or Firebase)
google-services.json

# Freeline
freeline.py
freeline/
freeline_project_description.json

# fastlane
fastlane/report.xml
fastlane/Preview.html
fastlane/screenshots
fastlane/test_output
fastlane/readme.md

# Version control
vcs.xml

# lint
lint/intermediates/
lint/generated/
lint/outputs/
lint/tmp/
lint-results.html

# Android Profiling
*.hprof
EOF

echo "📦 Hướng dẫn upload lên GitHub:"
echo ""
echo "1. Tạo repository mới trên GitHub.com"
echo "2. Copy repository URL (ví dụ: https://github.com/username/auto-click-tool.git)"
echo "3. Chạy các lệnh sau:"
echo ""
echo "   git remote add origin [YOUR_REPO_URL]"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "4. Sau khi push, GitHub Actions sẽ tự động build APK"
echo "5. APK sẽ có sẵn trong tab 'Actions' → Artifact downloads"
echo ""
echo "🎯 APK sẽ được build tự động và có sẵn để tải về!"
