name: Debug Build

on:
  workflow_dispatch:

jobs:
  debug-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: List project structure
      run: |
        echo "=== Project Root ==="
        ls -la
        echo "=== App Directory ==="
        ls -la app/
        echo "=== Gradle Wrapper ==="
        ls -la gradle/wrapper/
        echo "=== Source Directory ==="
        ls -la app/src/main/
        
    - name: Check Gradle files
      run: |
        echo "=== Root build.gradle.kts ==="
        cat build.gradle.kts
        echo "=== App build.gradle.kts ==="
        head -20 app/build.gradle.kts
        echo "=== gradle.properties ==="
        cat gradle.properties
        echo "=== settings.gradle.kts ==="
        cat settings.gradle.kts
        
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Test Gradle wrapper
      run: ./gradlew --version
      
    - name: Try clean build
      run: ./gradlew clean --stacktrace
      
    - name: List tasks
      run: ./gradlew tasks --all
