name: Minimal Test Build

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 34
        build-tools: 34.0.0
    
    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}
    
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    - name: Check Gradle version
      run: ./gradlew --version
    
    - name: Clean project
      run: ./gradlew clean
    
    - name: Build debug APK
      run: ./gradlew app:assembleDebug
    
    - name: List APK files
      run: find app/build/outputs -name "*.apk" -type f
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: minimal-test-apk
        path: app/build/outputs/apk/debug/*.apk
