name: Ultra Simple Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    - name: Clean
      run: ./gradlew clean
    
    - name: Assemble Debug
      run: ./gradlew assembleDebug --no-daemon --stacktrace
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: ultra-simple-apk
        path: app/build/outputs/apk/debug/app-debug.apk
